export const ROUTES = {
  BASE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: `/home`,
  IDEAL_COURSES: "/ideal-courses",
  RESUME: "/resume",
  PERSONALITY_TEST: "/personality-test",
  MEMBER_ANALYTICS: "/member-analytics",
  SHORTLIST: "/shortlist/:id",
  DEFAULT_SHORTLIST: "/shortlist",
  CLIENT_SHORTLIST: "/client/shortlist/:id",
  CLIENT_DEFAULT_SHORTLIST: "/client/shortlist",
  PROFILE: "/profile/:userId",
  LINK_EXPIRE: "/link-not-found",
  TOKEN_PROFILE: "/candidate/:token",
  OTHERS: "*",
  CLIENT_LIST: "/client/list",
  CLIENT_CREATE: "/client/create",
  CLIENT_PROFILE: "/client/:clientId/profile",
  CLIENT_GENERATE_PASSWORD: "/create-password",
  CLIENT_DASHBOARD: "/client",
};
