export const ROUTES = {
  BASE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: `/home`,
  IDEAL_COURSES: "/ideal-courses",
  RESUME: "/resume",
  PERSONALITY_TEST: "/personality-test",
  MEMBER_ANALYTICS: "/member-analytics",
  SHORTLIST: "/shortlist/:id",
  DEFAULT_SHORTLIST: "/shortlist",
  PROFILE: "/profile/:userId",
  TOKEN_PROFILE: "/candidate/:token",
  OTHERS: "*",
};
